apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 936819548906.dkr.ecr.us-east-1.amazonaws.com/frontend:2288d77899d8d1027389a64e4e8a0b8715575cdf
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://gateway:3001/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: boutique
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

